export default [
    {name: 'wardno', type:'string',label:'Ward Number:',fieldType:'input'},
    {name: 'buildingno', type:'string',label:'Building Number:',fieldType:'input'},
     {name: 'houseno',type:'string',label:'House No:',fieldType:'input'},
     {name: 'floor_material',type:'string',label:'Material of Floor',fieldType:'select',
     data:[{id:'1',label: 'Granite/Marble', value: 'granite_marble'}, 
            {id:'2',label: 'Lime Stone', value: 'limestone'},
            {id:'3',label: 'Cement Gatchu', value: 'cement'}, 
            {id:'4',label: 'Soil', value: 'soil'},  ]},
      {name: 'wall_material',type:'string',label:'Material of Wall',fieldType:'select',
     data:[{id:'1',label: 'Cement wall', value: 'cement_wall'}, 
            {id:'2',label: 'Rock wall', value: 'rockwall'},
            {id:'3',label: 'Soil/Grass', value: 'soil'}  ]},
      {name: 'roof_material',type:'string',label:'Material of Roof',fieldType:'select',
            data:[{id:'1',label: 'Slab', value: 'slab'}, 
                   {id:'2',label: 'Roof Tiles', value: 'roof_tiles'},
                   {id:'3',label: 'Cement Rekulu', value: 'cement_rekulu'},
                   {id:'4',label: 'Iron Rekulu', value: 'iron_rekulu'},
                   {id:'5',label: 'Mixture of Lime&Gud', value: 'matti_roof'},]},
      {name: 'house_condition',type:'string',label:'Condition of House',fieldType:'radio',
      data:[{id:'1',label: 'New/Good condition', value: 'new'}, 
            {id:'2',label: 'Old/Bad condition', value: 'old'} ]},
      {name: 'house_usefulness',type:'string',label:'House is in useful condtion?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'no_persons_belongs',type:'string',label:'Number of people belongs to house?',fieldType:'input'},
      {name: 'no_persons_outside',type:'string',label:'Number of people living out of station?',fieldType:'input'},
      {name: 'name_hoh',type:'string',label:'Name head of the house',fieldType:'input'},
      {name: 'ownership_with_hoh',type:'string',label:'Is ownership with head of the house?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'no_rooms',type:'string',label:'Number of rooms in the house',fieldType:'input'},
      {name: 'no_marride_couple',type:'string',label:'Number of married couple living in the house',fieldType:'input'},
      {name: 'source_drinking_water',type:'string',label:'Source of Drinking water?',fieldType:'select',
     data:[{id:'1',label: 'Bore Well', value: 'bore_well'}, 
            {id:'2',label: 'Tank Water', value: 'tank_water'},
            {id:'3',label: 'Pipeline Water', value: 'pipeline_water'}  ]},
      {name: 'availed_powerconnection',type:'string',label:'Is power connection avaialable?',fieldType:'radio',
            data:[{id:'1',label: 'Yes', value: 'yes'}, 
                  {id:'2',label: 'No', value: 'no'} ]},
      {name: 'latrine_type',type:'string',label:'Type of Latrine?',fieldType:'select',
      data:[{id:'1',label: 'Pit Latrine', value: 'pit'}, 
                  {id:'2',label: 'Ventilated Improved Pit', value: 'vantilated'},
                  {id:'3',label: 'Flush type', value: 'flush'},
                  {id:'4',label: 'Facilities shared between many', value: 'shared_btwn_many'},]},
      {name: 'waste_water_outlet',type:'string',label:'Waste water outlet',fieldType:'select',
      data:[{id:'1',label: 'No Proper Outlet', value: 'no_proper_outlet'}, 
                  {id:'2',label: 'Open Canals', value: 'open_canals'},
                  {id:'3',label: 'Closed Outlets', value: 'closed_outlet'}  ]},
      {name: 'bathing_facility',type:'string',label:'Is Bathing facility avaialable?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'lpg_cng_connection',type:'string',label:'Is LPG/CNG connection avaialable?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'main_fuel_cooking',type:'string',label:'Main fuel used for cooking',fieldType:'select',
      data:[{id:'1',label: 'LPG/CNG', value: 'lpg_cng'}, 
            {id:'2',label: 'Vanta Kalapa', value: 'kalapa'},
            {id:'3',label: 'Dung Cakes', value: 'dung_cake'},
            {id:'4',label: 'Electric stove', value: 'electric_stove'},
            {id:'5',label: 'Kerocine stove', value: 'kerocine_stove'},
            {id:'6',label: 'Biogas', value: 'bio_gas'},]},
      {name: 'smart_phone_availability',type:'string',label:'Is smartphone avaialable?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'tv_availability',type:'string',label:'Is Television avaialable?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},

      {name: 'computer_availability',type:'string',label:'Is Computer avaialable?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},

      {name: 'broadband_availability',type:'string',label:'Is Broadband/Internet avaialable?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},

      {name: 'telephone_availability',type:'string',label:'Is telephone avaialable?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},

      {name: 'twowheeler_availability',type:'string',label:'Owns any two wheeler like byke or scooty?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'auto_availability',type:'string',label:'Owwns Auto?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},


      {name: 'fourwheeler_availability',type:'string',label:'Owwns four wheeler like Car/Jeep/Van?',fieldType:'radio',
            data:[{id:'1',label: 'Yes', value: 'yes'}, 
                  {id:'2',label: 'No', value: 'no'} ]},

      {name: 'tractor_availability',type:'string',label:'Owns Trator?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},

      {name: 'lorry_bus_availability',type:'string',label:'Owns big vehicle like Lorry or Bus?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'main_cereal_used',type:'string',label:'Main food consumed?',fieldType:'radio',
      data:[{id:'1',label: 'Rice', value: 'rice'}, 
            {id:'2',label: 'Atta', value: 'atta'} ]},
      {name: 'owns_business',type:'string',label:'Owns any type of Business?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'type_of_business',type:'string',label:'Type of Business',fieldType:'select',
      data:[{id:'1',label: 'Small/Kirana/Cloaths Shop', value: 'micro'}, 
            {id:'2',label: 'Medium/1 Crore turnover', value: 'medium'},
            {id:'3',label: 'Big/Above 10 crore', value: 'big'},]},
      {name: 'owns_maggam',type:'string',label:'Owns Maggam?',fieldType:'radio',
      data:[{id:'1',label: 'Yes', value: 'yes'}, 
            {id:'2',label: 'No', value: 'no'} ]},
      {name: 'acre_agri_land',type:'string',label:'Agriculure land owned in acres:',fieldType:'input'},

    //  {name: 'date',type:'string',label:'Date of Birth',fieldType:'date'},
    //  {name: 'gender',type:'string',label:'Gender',fieldType:'select',data:[{id:'1',label: 'Female', value: 'female'}, {id:'2',label: 'Male', value: 'male'},{id:'3',label: 'Other', value: 'other'},  ]},
    // {name: 'option',type:'string',label:'Company',fieldType:'radio',data :[
    //   {id:'1', value: 'Apple',label: 'Apple' },
    //   { id:'2',value: 'Samsung' ,label: 'Samsung'},
    //   {id:'3', value: 'Blackberry',label: 'Blackberry' },
    // ]},
  ];
  